import { Link } from "react-router-dom";
import "./Documentation.css";

export default function Documentation() {
  const downloadGuide = () => {
    // Create a simple text guide
    const guideContent = `# OTP SaaS Setup Guide

## Welcome to OTP SaaS!
This guide will help you get started with OTP SaaS for secure email authentication.

## Quick Start

### 1. Create an Account
- Visit https://otpsaas.com
- Click "Sign Up" and create your account
- Verify your email address

### 2. Generate API Key
- Go to your Dashboard > API Keys
- Click "Create New API Key"
- Copy the generated key (keep it secure!)

### 3. Configure SMTP
- Go to Dashboard > SMTP Configuration
- Add your SMTP server details:
  - Host: smtp.gmail.com (or your provider)
  - Port: 587 (TLS) or 465 (SSL)
  - Email: your-email@gmail.com
  - Password: your-app-password

### 4. Create Email Template
- Go to Dashboard > Templates
- Click "Create New Template"
- Design your OTP email with {{OTP}} placeholder

### 5. Send Your First OTP
Use the API to send OTP:

\`\`\`javascript
// JavaScript Example
const response = await fetch('https://api.otpsaas.com/v1/otp/send', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer YOUR_API_KEY'
  },
  body: JSON.stringify({
    recipient: 'user@example.com',
    templateName: 'Your Template Name'
  })
});

const result = await response.json();
console.log('OTP sent:', result.otp);
\`\`\`

### 6. Verify OTP
\`\`\`javascript
// Verify the OTP
const verifyResponse = await fetch('https://api.otpsaas.com/v1/otp/verify', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer YOUR_API_KEY'
  },
  body: JSON.stringify({
    otp: '123456'
  })
});

const verifyResult = await verifyResponse.json();
console.log('Verified:', verifyResult.success);
\`\`\`

## API Reference

### Send OTP
POST /v1/otp/send

Headers:
- Content-Type: application/json
- Authorization: Bearer YOUR_API_KEY

Body:
{
  "recipient": "user@example.com",
  "templateName": "Default OTP"
}

Response:
{
  "success": true,
  "message": "OTP sent successfully",
  "otp": "123456"
}

### Verify OTP
POST /v1/otp/verify

Headers:
- Content-Type: application/json
- Authorization: Bearer YOUR_API_KEY

Body:
{
  "otp": "123456"
}

Response:
{
  "success": true,
  "message": "OTP verified successfully"
}

## Troubleshooting

### Common Issues

1. **SMTP Connection Failed**
   - Check your SMTP credentials
   - Verify firewall settings
   - Ensure correct port (587 for TLS, 465 for SSL)

2. **Template Not Found**
   - Verify template name matches exactly
   - Check if template exists in your account

3. **API Key Invalid**
   - Regenerate your API key
   - Ensure correct Bearer token format

### Support
- Email: support@otpsaas.com
- Documentation: https://otpsaas.com/docs
- Help Center: https://otpsaas.com/support

## Security Best Practices

1. Store API keys securely
2. Use HTTPS for all API calls
3. Implement rate limiting
4. Validate user input
5. Monitor API usage

---
Generated by OTP SaaS - Secure Authentication Made Simple
`;

    const blob = new Blob([guideContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'otp-saas-setup-guide.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="documentation-page">
      <div className="page-header">
        <div className="container">
          <h1>Documentation</h1>
          <p>Everything you need to integrate OTP SaaS into your application.</p>
          <button onClick={downloadGuide} className="btn-primary download-btn">
            📥 Download Setup Guide
          </button>
        </div>
      </div>

      <div className="container">
        <div className="doc-navigation">
          <div className="nav-section">
            <h3>Getting Started</h3>
            <ul>
              <li><a href="#quick-start">Quick Start Guide</a></li>
              <li><a href="#authentication">Authentication</a></li>
              <li><a href="#smtp-setup">SMTP Configuration</a></li>
            </ul>
          </div>
          <div className="nav-section">
            <h3>API Reference</h3>
            <ul>
              <li><Link to="/support/api-reference">Send OTP</Link></li>
              <li><Link to="/support/api-reference">Verify OTP</Link></li>
              <li><Link to="/support/api-reference">Templates</Link></li>
              <li><Link to="/support/api-reference">Logs</Link></li>
            </ul>
          </div>
          <div className="nav-section">
            <h3>SDKs</h3>
            <ul>
              <li><a href="#javascript">JavaScript</a></li>
              <li><a href="#python">Python</a></li>
              <li><a href="#php">PHP</a></li>
              <li><a href="#java">Java</a></li>
            </ul>
          </div>
        </div>

        <section id="quick-start" className="doc-section">
          <h2>Quick Start Guide</h2>
          <div className="steps">
            <div className="step">
              <div className="step-number">1</div>
              <div className="step-content">
                <h3>Create Your Account</h3>
                <p>Sign up for a free account at <Link to="/register">otpsaas.com</Link>. Verify your email to get started.</p>
              </div>
            </div>
            <div className="step">
              <div className="step-number">2</div>
              <div className="step-content">
                <h3>Generate API Key</h3>
                <p>In your dashboard, navigate to API Keys and create a new key. Keep this key secure as it's required for all API calls.</p>
              </div>
            </div>
            <div className="step">
              <div className="step-number">3</div>
              <div className="step-content">
                <h3>Configure SMTP</h3>
                <p>Set up your email provider in the SMTP Configuration section. We support Gmail, SendGrid, Mailgun, and custom SMTP servers.</p>
              </div>
            </div>
            <div className="step">
              <div className="step-number">4</div>
              <div className="step-content">
                <h3>Create Email Template</h3>
                <p>Design your OTP email template using our visual editor. Use the <code>{`{OTP}`}</code> placeholder where you want the code to appear.</p>
              </div>
            </div>
            <div className="step">
              <div className="step-number">5</div>
              <div className="step-content">
                <h3>Send Your First OTP</h3>
                <p>Use our API to send your first OTP. Check the code examples below for your preferred language.</p>
              </div>
            </div>
          </div>
        </section>

        <section id="authentication" className="doc-section">
          <h2>Authentication</h2>
          <p>All API requests require authentication using your API key. Include the key in the Authorization header:</p>

          <div className="code-example">
            <pre><code>Authorization: Bearer YOUR_API_KEY</code></pre>
          </div>

          <div className="security-note">
            <h4>🔒 Security Note</h4>
            <p>Keep your API key secure and never expose it in client-side code. Rotate keys regularly and revoke compromised keys immediately.</p>
          </div>
        </section>

        <section id="smtp-setup" className="doc-section">
          <h2>SMTP Configuration</h2>
          <p>Configure your SMTP settings to enable email delivery. Here's how to set up popular providers:</p>

          <div className="smtp-providers">
            <div className="provider-config">
              <h3>Gmail</h3>
              <ul>
                <li><strong>Host:</strong> smtp.gmail.com</li>
                <li><strong>Port:</strong> 587 (TLS) or 465 (SSL)</li>
                <li><strong>Username:</strong> your-email@gmail.com</li>
                <li><strong>Password:</strong> App Password (not your regular password)</li>
              </ul>
              <p><small>Note: Enable 2-factor authentication and generate an App Password</small></p>
            </div>

            <div className="provider-config">
              <h3>SendGrid</h3>
              <ul>
                <li><strong>Host:</strong> smtp.sendgrid.net</li>
                <li><strong>Port:</strong> 587</li>
                <li><strong>Username:</strong> apikey</li>
                <li><strong>Password:</strong> Your SendGrid API key</li>
              </ul>
            </div>

            <div className="provider-config">
              <h3>Mailgun</h3>
              <ul>
                <li><strong>Host:</strong> smtp.mailgun.org</li>
                <li><strong>Port:</strong> 587</li>
                <li><strong>Username:</strong> Your Mailgun SMTP username</li>
                <li><strong>Password:</strong> Your Mailgun SMTP password</li>
              </ul>
            </div>
          </div>
        </section>

        <section id="javascript" className="doc-section">
          <h2>JavaScript SDK</h2>
          <div className="install-code">
            <pre><code>npm install otp-saas</code></pre>
          </div>

          <div className="code-example">
            <pre><code>{`import { OTPClient } from 'otp-saas';

const client = new OTPClient({
  apiKey: 'YOUR_API_KEY',
  baseURL: 'https://api.otpsaas.com'
});

// Send OTP
try {
  const result = await client.sendOTP({
    recipient: 'user@example.com',
    templateName: 'Welcome OTP'
  });
  console.log('OTP sent:', result.otp);
} catch (error) {
  console.error('Error:', error.message);
}

// Verify OTP
try {
  const verified = await client.verifyOTP({
    otp: '123456'
  });
  console.log('Verified:', verified.success);
} catch (error) {
  console.error('Error:', error.message);
}`}</code></pre>
          </div>
        </section>

        <section id="python" className="doc-section">
          <h2>Python SDK</h2>
          <div className="install-code">
            <pre><code>pip install otp-saas</code></pre>
          </div>

          <div className="code-example">
            <pre><code>{`from otp_saas import OTPClient

client = OTPClient(
    api_key='YOUR_API_KEY',
    base_url='https://api.otpsaas.com'
)

# Send OTP
try:
    result = client.send_otp(
        recipient='user@example.com',
        template_name='Welcome OTP'
    )
    print('OTP sent:', result['otp'])
except Exception as e:
    print('Error:', str(e))

# Verify OTP
try:
    verified = client.verify_otp(otp='123456')
    print('Verified:', verified['success'])
except Exception as e:
    print('Error:', str(e))`}</code></pre>
          </div>
        </section>

        <section className="doc-cta">
          <h2>Need More Help?</h2>
          <p>Can't find what you're looking for? Our support team is here to help.</p>
          <div className="cta-buttons">
            <Link to="/support/help-center" className="btn-primary">Visit Help Center</Link>
            <a href="mailto:support@otpsaas.com" className="btn-secondary">Contact Support</a>
          </div>
        </section>
      </div>
    </div>
  );
}
